# Generated by Django 4.1 on 2022-10-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_userbookshelf_book_userbookshelf_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(choices=[('UCLA', 'University of California'), ('USC', 'University of Southern Californa'), ('CSUF', 'Cal State Fullerton '), ('HIU', 'Hope International University')], default=None, max_length=100),
        ),
    ]
